### PR TITLE
0.6.0

### PR DESCRIPTION
**Pull request by cvrebert**
CC: @desandro

### CODE REVIEW

**Comment by desandro** [comment]
thanks for this

**Comment by cvrebert** [comment]
@desandro No sweat. Can you publish to npm?

**Comment by desandro** [comment]
@sheerun Can you publish or add me to collaborators?

**Comment by sheerun** [comment]
@desandro I've added you to most of the projects :)

**Comment by desandro** [comment]
Published `bower-json@0.6.0` to [npm](https://www.npmjs.com/package/bower-json)

**Pull request merged**
