### PR TITLE
extend validation capabilities

### PR DESCRIPTION
**Pull request by gronke**
Extended the validation function, so that it also validates dependency names.

Necessary according to fix:
- https://github.com/bower/bower/issues/1887
- https://github.com/bower/bower/issues/1888

### CODE REVIEW

**Comment by faceleg** [comment]
@sheerun, @gronke's issue https://github.com/bower/bower/issues/1886#issuecomment-157930157
strikes me as pretty important, can we have a look at merging this to support the merging of https://github.com/bower/bower/pull/1892?

**Comment by sheerun** [comment]
But please instead throwing an error, return an array of errors.. It's important if we want to implement "bower validate" or similar command. Throwing means we can only get one error at a time..

**Comment by gronke** [comment]
Scope of this PR was to improve the validation, not to implement additional interfaces. More features are welcome, but I'm in favor of putting them in another PR.

`validate()` still provides the same interface, but the exposed `findErrors()` function returns an array of errors and can be used for future commands that require a full list of errors.

**Comment by sheerun** [comment]
Incorporated in master as slightly refactored `getIssues` method.

**Pull request closed without merging**
